### ISSUE TITLE
Get Zumero working on client and server

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/ProjectCrystalBlue#11]

**Comment by hoodlm** [comment]
Just to document our status as of right now:
- We have been in communication with the Zumero support team and found out that there is an existing issue with Zumero in OS X Mavericks.
- The support team sent us a supposedly fixed version, but the issue is still present.
- Support is in communication with devs to attain a hotfix and/or estimate a timetable for when the issue will be fixed. As of 5:49 PM on 10 Dec Justin just got an email with another fixed version that we are going to try.

All of us are running OS X Mavericks on our Macs, but we have an acquaintance with a MacBook running 10.8. We will also try to run our app on his machine. If we are able to do so, and successfully synchronize two different clients, we'll capture a video and send it to Dr. Vidal.

**Comment by hoodlm** [comment]
Another update: The hotfix they sent us did work. We have the databases successfully synchronizing between two different _desktop_ clients. There is an error that we're still experiencing on the mobile version.

**Comment by hoodlm** [comment]
Zumero is successfully running on the OS X app: https://www.dropbox.com/s/v4sw8lpertdrwxl/VID_20131213_003814.mp4

There are still pending mobile issues.
