### ISSUE TITLE
Allow user to edit sample from table screen

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/ProjectCrystalBlue#15]

**Comment by hoodlm** [comment]
We're going to disable this functionality entirely for right now, due to some items having restricted values (e.g. the Rock Type can only be from a small set of values: Igneus, Metamorphic, etc.).

If we have time to integrate in-table drop-down menus and that sort of thing, we'll reconsider adding in-table editing. Closing this issue for right now.
