### ISSUE TITLE
OS X: User is able to save new source without entering information.

### ISSUE THREAD

**Issue by ghost** [SCCapstone/ProjectCrystalBlue#41]
Fields are left with default text. Make default text a placeholder instead of an actual value.

**Comment by hoodlm** [comment]
Fixed - these are now placeholder texts.

The only exceptions to this are:
Date Collected - must have a valid value when creating a source, so we have a default date set to the current time
Notes/Hyperlinks - Since they are NSTextView, rather than NSTextField, they don't support a placeholder text. So we're leaving the Notes field blank by default, and including a sample link to http://www.geol.sc.edu in the Hyperlinks field.

**Comment by hoodlm** [comment]
https://github.com/SCCapstone/ProjectCrystalBlue/commit/f5821a98ed15fe73398f241956a27f5b977b2a22
